sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t msazureelf/docker-react .

script:
  - docker run -e CI=true msazureelf/docker-react npm run test

